language: php
php:
  - '7.3'
services:
  - mysql

before_script:
  - composer install
  - export PATH=http://localhost:8000/

script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - vendor/bin/behat
  - vendor/bin/behat --strict
  - phpunit
  - phpunit --coverage-text
