language: php
php:
  - '7.3'
services:
  - mysql

notifications:
    email: false

before_script:
  - composer install


script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console cache:clear --env=test
  - vendor/bin/behat features/login.feature:11
  - phpunit
  - phpunit --coverage-text
