language: php
php:
  - '7.3'
services:
  - mysql

notifications:
    email: false

before_script:
  - composer install


script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console cache:clear
  - vendor/bin/behat
  - vendor/bin/behat --strict
  - phpunit
  - phpunit --coverage-text
