language: php
php:
  - '7.3'
services:
  - mysql

install:
  - composer install --no-progress

before_script:
  - export PATH=./vendor/bin:$PATH

script:
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - vendor/bin/behat
  - vendor/bin/phpunit
  - vendor/bin/phpunit --coverage-text
